ungrouped:
  hosts:
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
      #ansible_become: yes
      #ansible_become_method: sudo 
  children:
    aic_hosts:
      vars:
        regional_settings: "ru"
        time_settings:
          ntp_servers:
            - '0.ru.pool.ntp.org iburst'
            - 1.ru.pool.ntp.org
            - 2.ru.pool.ntp.org
            - 3.ru.pool.ntp.org
          timezone: "Europe/Moscow"
        dns_servers:
          - 192.168.16.30
          - 192.168.16.31
        search_lists:
          - aic.company.com
          - company.com
      children:
        prepare_fresh_hosts:
          vars:
            a: b
          hosts:
            192.168.16.12:
              net_config:
                hostname: srv-01
                bondings:
                - name: bond0 #native (management) vlan?
                  mode: active-passive
                  primary_interface: enp1s0
                  members:
                    - enp1s0 # initially management interface
                    - enp7s0
                  ip_settings: #адрес не нужен, если сверху будет мост и машины в management vlan-е, иначе можно указать, шлюз должен быть только один, в остальных случаях - none
                    address: none # 192.168.16.12/24
                    gateway: none # 192.168.16.1
                - name: bond1 # LACP -- не протестировать (
                  mode: active-passive
                  primary_interface: enp9s0
                  members:
                    - enp9s0
                    - enp10s0
                  ip_settings: #адрес не нужен, если сверху будет мост и машины в management vlan-е
                    address: 192.168.50.1/24 #none # none - сверху будет мост с адресом. адрес должен быть либо у моста, либо у тиминга
                    gateway: none
                vlans:
                  vlan_interfaces:
                    system:
                      - name: 20 #backup vlan
                        parent_interface: bond0
                        ip_settings:
                          address: none # 192.168.20.9/24
                          gateway: none # 192.168.20.1
                      - name: 30 # iscsi vlan
                        parent_interface: bond0
                        ip_settings:
                          address: none # 192.168.30.9/24
                          gateway: none # 192.168.30.1
                    guests:
                      - name: 40 # guest vlan-40
                        parent_interface: bond0
                        ip_settings:
                          address: none
                          gateway: none 
                bridges:
                  bridge_interfaces:
                    system:
                      - name: br-sys-mgmt #management vlan
                        parent_interface: bond0
                        ip_settings:
                          address: 192.168.16.12/24
                          gateway: 192.168.16.1
                      - name: br-sys-storage # iscsi vlan
                        parent_interface: bond0.20
                        ip_settings:
                          address: 192.168.20.9/24
                          gateway: none # 192.168.20.1
                      - name: br-sys-backup # backup vlan
                        parent_interface: bond0.30
                        ip_settings:
                          address: 192.168.30.9/24
                          gateway: none # 192.168.30.1
                    guests:
                      - name: br-gst-vlan40
                        parent_interface: bond0.40
                        ip_settings:
                          address: none
                          gateway: none
